--trigger
--mục tiêu: cài đặt các ràng buộc toàn vẹn
--cài trên 1 bảng (quan hệ)
--cú pháp
--CREATE 
----ALTER
--TRIGGER UTR_1 
--ON QUANHE
--FOR INSERT, UPDATE, DELETE
--AS
--	--ĐIỀU KIỆN KIỂM TRA
--	IF ()
--	BEGIN
--		--XỬ LÍ ĐẢM TÍNH TOÀN VẸN DỮ LIÊU
--		RAISERROR('THONG BAO', 16,1) --;THROW 5000,'THONG BAO', 1
--	END
--GO
--TRIGGER KIỂM TRA ĐIỀU KIỆN -> THÔNG BÁO
--RB1: SỐ CÔNG VIỆC CỦA GIÁO VIÊN ĐANG THỰC HIỆN < 5
SELECT * FROM THAMGIADT
GO
CREATE 
--ALTER
TRIGGER UTR_RB1 
ON THAMGIADT
FOR INSERT
AS
	--ĐIỀU KIỆN KIỂM TRA VI PHẠM
	IF EXISTS (SELECT * FROM THAMGIADT TG JOIN
			inserted I ON I.MAGV = TG.MAGV
			WHERE TG.KETQUA IS NULL
			HAVING COUNT(*) >=5) 
	BEGIN
		--XỬ LÍ ĐẢM TÍNH TOÀN VẸN DỮ LIÊU
		RAISERROR('THONG BAO', 16,1) --;THROW 5000,'THONG BAO', 1
		ROLLBACK TRAN
	END
GO

--TRIGGER KIỂM TRA ĐIỀU KIỆN -> XỬ LÍ
--RB2: SỐ CÔNG VIỆC > 5 PHÂN CÔNG VIỆC ĐÓ CHO GV KHÁC
CREATE 
--ALTER
TRIGGER UTR_RB2 
ON THAMGIADT
FOR INSERT
AS
	--ĐIỀU KIỆN KIỂM TRA VI PHẠM
	IF EXISTS (SELECT * FROM THAMGIADT TG JOIN
			inserted I ON I.MAGV = TG.MAGV
			WHERE TG.KETQUA IS NULL
			HAVING COUNT(*) >=5) 
	BEGIN
		--XỬ LÍ ĐẢM TÍNH TOÀN VẸN DỮ LIÊU
		--TÌM MÃ GIÁO VIÊN THỎA ĐIỀU KIỆN THAMGIA
		DELETE THAMGIADT FROM inserted I
		WHERE THAMGIADT.MAGV = I.MAGV AND
		THAMGIADT.STT = I.STT AND
		THAMGIADT.MADT = I.MADT
		DECLARE @MAGV VARCHAR(4) = (SELECT TOP 1 MAGV
									FROM GIAOVIEN GV
									WHERE MAGV NOT IN (SELECT MAGV
														FROM THAMGIADT TG
														WHERE KETQUA IS NULL
														GROUP BY MAGV
														HAVING COUNT(*) >= 4))
		INSERT THAMGIADT 
		SELECT DBO.F_1(), I.MADT,I.STT,I.PHUCAP,I.KETQUA
		FROM inserted I
	END
GO
INSERT THAMGIADT (MAGV, MADT, STT)
VALUES('009','001',1)
SELECT * FROM THAMGIADT
--proc
--MỤC TIÊU: GOM CÁC CÂU TRUY VẤN THÀNH CHƯƠNG TRÌNH -> THỰC HIỆN MỤC ĐÍCH NÀO ĐÓ
GO
CREATE OR ALTER
--ALTER
PROC SP_1 
	@MAGV VARCHAR(4),
	@MADT VARCHAR(4),
	@STT INT
AS
	IF EXISTS (SELECT * FROM THAMGIADT WHERE MAGV = @MAGV
	AND MADT=@MADT AND STT = @STT)
	BEGIN
		PRINT 'LOI'
		RETURN 
	END
	INSERT THAMGIADT (MAGV, MADT, STT)
	VALUES(@MAGV, @MADT,@STT)
EXEC SP_1 '001','002',1
--function
--LOẠI TRẢ VỀ GIÁ TRỊ
GO
CREATE FUNCTION F_1 ()
RETURNS VARCHAR(4)
AS
BEGIN
	RETURN (SELECT TOP 1 MAGV
			FROM GIAOVIEN GV
			WHERE MAGV NOT IN (SELECT MAGV
								FROM THAMGIADT TG
								WHERE KETQUA IS NULL
								GROUP BY MAGV
								HAVING COUNT(*) >= 4))
END
SELECT DBO.F_1 ()
--LOẠI TRẢ VỀ BẢNG
--LẤY DANH SÁCH CÁC GV CÓ THỂ PHÂN CÔNG
GO
CREATE FUNCTION F_2()
RETURNS TABLE
AS
	RETURN (SELECT MAGV
			FROM GIAOVIEN GV
			WHERE MAGV NOT IN (SELECT MAGV
								FROM THAMGIADT TG
								WHERE KETQUA IS NULL
								GROUP BY MAGV
								HAVING COUNT(*) >= 4))
SELECT * FROM F_2()
