name: DS-env
channels: 
- conda-forge
dependencies:
- jupyterlab=3.6.3
- jupyter_contrib_nbextensions=0.5.1
- requests=2.31.0
- requests-cache=1.1.0
- urllib3=1.26.6
- beautifulsoup4=4.12.2
- selenium=3.141.0
- python-chromedriver-binary=114.0.5735.90.0
- matplotlib=3.8.0
- numpy=1.26.0
- pandas=2.1.1
- openpyxl=3.1.2 # Help pandas read excel files
- scikit-learn=1.3.1
- nbdime=3.2.1
- seaborn=0.12.2